##############
# Settings for the main Pega to Lego Controller app
##############

robotId: "Pega One" # Bluetooth identification name that is also used in Pega
baseUrl: "https://XXXXXXXXXXXXXXXXX/prweb/api/PegaBotController/1/" # Base url of the controller API
userName: "username" # Pega user identifier
password: "password" # Pega user identifier password